# Generated by Django 5.1.4 on 2024-12-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(blank=True, choices=[('majuscule_letter', 'Majuscule Letter'), ('minuscule_letter', 'Minuscule Letter'), ('numeral', 'Numeral'), ('punctuation', 'Punctuation'), ('symbol', 'Symbol'), ('accent', 'Accent')], max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllographComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols_structure.allograph')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols_structure.component')),
            ],
        ),
        migrations.AddField(
            model_name='allograph',
            name='aspects',
            field=models.ManyToManyField(blank=True, related_name='allographs', to='symbols_structure.aspect'),
        ),
        migrations.AddField(
            model_name='allograph',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols_structure.character'),
        ),
        migrations.AddField(
            model_name='allograph',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='allographs', through='symbols_structure.AllographComponent', to='symbols_structure.component'),
        ),
        migrations.AddField(
            model_name='component',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='components', to='symbols_structure.feature'),
        ),
        migrations.CreateModel(
            name='AllographComponentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_by_default', models.BooleanField(default=False)),
                ('allograph_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols_structure.allographcomponent')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols_structure.feature')),
            ],
            options={
                'unique_together': {('allograph_component', 'feature')},
            },
        ),
        migrations.AddField(
            model_name='allographcomponent',
            name='features',
            field=models.ManyToManyField(through='symbols_structure.AllographComponentFeature', to='symbols_structure.feature'),
        ),
        migrations.AlterUniqueTogether(
            name='allographcomponent',
            unique_together={('allograph', 'component')},
        ),
    ]
