# Generated by Django 5.1.1 on 2024-10-04 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetext',
            name='item_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='manuscripts.itemimage'),
        ),
    ]
