# Generated by Django 5.1.1 on 2024-10-20 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0002_alter_imagetext_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='item_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manuscripts.itempart'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
