# Generated by Django 5.1.2 on 2024-10-27 15:28

import djiiif
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0003_alter_itemimage_item_part_alter_repository_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='date_sort',
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=djiiif.IIIFField(upload_to='historical_items'),
        ),
    ]
