# Generated by Django 5.1.4 on 2024-12-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuscripts', '0001_initial'),
        ('scribes', '0001_initial'),
        ('symbols_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.JSONField()),
                ('allograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols_structure.allograph')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scribes.hand')),
                ('item_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='manuscripts.itemimage')),
            ],
        ),
        migrations.CreateModel(
            name='GraphComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols_structure.component')),
                ('features', models.ManyToManyField(blank=True, to='symbols_structure.feature')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotations.graph')),
            ],
            options={
                'unique_together': {('graph', 'component')},
            },
        ),
        migrations.AddField(
            model_name='graph',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='graphs', through='annotations.GraphComponent', to='symbols_structure.component'),
        ),
    ]
