# Generated by Django 5.1.1 on 2024-09-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuscripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('scriptorium', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('item_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manuscripts.itempart')),
            ],
        ),
        migrations.CreateModel(
            name='HandToItemPartImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scribes.hand')),
                ('item_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manuscripts.itempart')),
            ],
        ),
        migrations.AddField(
            model_name='hand',
            name='item_part_images',
            field=models.ManyToManyField(related_name='hands', through='scribes.HandToItemPartImages', to='manuscripts.itempart'),
        ),
        migrations.AddField(
            model_name='hand',
            name='scribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scribes.scribe'),
        ),
        migrations.AddField(
            model_name='hand',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scribes.script'),
        ),
    ]
