# Generated by Django 5.1.1 on 2024-11-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scribes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handtoitempartimages',
            options={'verbose_name_plural': 'Hands x Item Parts'},
        ),
    ]
