# Generated by Django 5.1.4 on 2024-12-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribes', '0002_alter_handtoitempartimages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scribe',
            name='period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scribe',
            name='scriptorium',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
