# Generated by Django 5.1.4 on 2024-12-17 23:41

import tagulous.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='keywords',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=10, to='publications.tagulous_publication_keywords'),
        ),
    ]
