# Generated by Django 5.1.2 on 2024-11-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordering')),
                ('image', models.ImageField(help_text='The image for this item', upload_to='carousel')),
                ('title', models.CharField(help_text='The caption under the image of this item. This can contain some inline HTML.', max_length=150)),
                ('url', models.URLField(help_text='The URL of the page this item links to. E.g. /digipal/page/80/ or https://www.digipal.eu/')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
