# Generated by Django 5.1.1 on 2024-09-24 15:28

import froala_editor.fields
import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_keywords_alter_publication_status'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='tags',
        ),
        migrations.AlterField(
            model_name='publication',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='preview',
            field=froala_editor.fields.FroalaField(default='preview'),
            preserve_default=False,
        ),
    ]
