# Generated by Django 5.1.4 on 2024-12-18 19:34

from django.db import migrations

from django.contrib.auth import get_user_model

User = get_user_model()

SUPER_USERS_NAMES = ["ahmed", "ali", "faidon", "luca", "stewart"]
def create_superusers(apps, schema_editor):
    for name in SUPER_USERS_NAMES:
        User.objects.create_superuser(
            username=name,
            email=f"{name}@archetype-pal.github.placeholder",
            password="123"
        )

def remove_superusers(apps, schema_editor):
    for username in SUPER_USERS_NAMES:
        User.objects.get(username=username).delete()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_superusers, remove_superusers),
    ]
