# Generated by Django 5.1.2 on 2024-12-04 19:28
from django.db import migrations
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User


SUPER_USERS_NAMES = ["ahmed", "ali", "faidon", "luca", "stewart"]
def create_superusers(apps, schema_editor):
    User = get_user_model()
    for name in SUPER_USERS_NAMES:
        User.objects.create_superuser(
            username=name,
            email=f"{name}@archetype-pal.github.placeholder",
            password="123"
        )

def remove_superusers(apps, schema_editor):
    for username in SUPER_USERS_NAMES:
        User.objects.get(username=username).delete()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_superusers, remove_superusers),
    ]
