# Generated by Django 5.1.1 on 2024-09-24 21:36

from django.db import migrations
from django.contrib.auth import get_user_model


def create_superuser(apps, schema_editor):
    User = get_user_model()

    User.objects.create_superuser(
        email='ahmed@home.com',
        password='123',
    )
    User.objects.create_superuser(
        email='ali@home.com',
        password='123',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
