# Generated by Django 5.1.1 on 2024-09-24 14:28

from django.db import migrations
from django.contrib.auth import get_user_model


def create_superuser(apps, schema_editor):
    User = get_user_model()

    User.objects.create_superuser(
        email='ahmed@home.com',
        password='1',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
