# Generated by Django 5.1.1 on 2024-10-04 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handwriting', '0001_initial'),
        ('manuscripts', '0002_alter_imagetext_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='item_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='manuscripts.itemimage'),
        ),
    ]
