# Generated by Django 5.1 on 2024-09-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("handwriting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="components",
            field=models.ManyToManyField(to="handwriting.component"),
        ),
    ]
