# Generated by Django 5.1.1 on 2024-11-08 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handwriting', '0002_alter_graph_item_image'),
        ('scribes', '0002_alter_handtoitempartimages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='location',
            new_name='annotation',
        ),
        migrations.RemoveField(
            model_name='character',
            name='form',
        ),
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.CharField(blank=True, choices=[('majuscule_letter', 'Majuscule Letter'), ('minuscule_letter', 'Minuscule Letter'), ('numeral', 'Numeral'), ('punctuation', 'Punctuation'), ('symbol', 'Symbol'), ('accent', 'Accent')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='hand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='scribes.hand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='features',
            field=models.ManyToManyField(related_name='components', to='handwriting.feature'),
        ),
        migrations.CreateModel(
            name='AllographComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handwriting.allograph')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handwriting.component')),
            ],
        ),
        migrations.AddField(
            model_name='allograph',
            name='components',
            field=models.ManyToManyField(related_name='allographs', through='handwriting.AllographComponent', to='handwriting.component'),
        ),
        migrations.CreateModel(
            name='AllographComponentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_by_default', models.BooleanField(default=False)),
                ('allograph_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handwriting.allographcomponent')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handwriting.feature')),
            ],
            options={
                'unique_together': {('allograph_component', 'feature')},
            },
        ),
        migrations.AddField(
            model_name='allographcomponent',
            name='features',
            field=models.ManyToManyField(through='handwriting.AllographComponentFeature', to='handwriting.feature'),
        ),
        migrations.AddField(
            model_name='allograph',
            name='aspects',
            field=models.ManyToManyField(related_name='allographs', to='handwriting.aspect'),
        ),
        migrations.AlterUniqueTogether(
            name='allographcomponent',
            unique_together={('allograph', 'component')},
        ),
    ]
