# Generated by Django 5.1.4 on 2024-12-17 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handwriting', '0003_aspect_rename_location_graph_annotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allograph',
            name='aspects',
            field=models.ManyToManyField(blank=True, related_name='allographs', to='handwriting.aspect'),
        ),
        migrations.AlterField(
            model_name='allograph',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='allographs', through='handwriting.AllographComponent', to='handwriting.component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='components', to='handwriting.feature'),
        ),
        migrations.CreateModel(
            name='GraphComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handwriting.component')),
                ('features', models.ManyToManyField(blank=True, to='handwriting.feature')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handwriting.graph')),
            ],
            options={
                'unique_together': {('graph', 'component')},
            },
        ),
        migrations.AlterField(
            model_name='graph',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='graphs', through='handwriting.GraphComponent', to='handwriting.component'),
        ),
    ]
